name: Deploy static site to GitHub Pages on push to master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run deploy
        env:
          GIT_USER: ${{ secrets.GITHUB_TOKEN }}
